"""empty message

Revision ID: bbf17d469dfe
Revises: f1ff96c6db5f
Create Date: 2022-05-29 14:34:01.132204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbf17d469dfe'
down_revision = 'f1ff96c6db5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_hunt', 'update_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('job_notice', 'update_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('job_open', 'update_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('user', 'updated',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'updated',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('job_open', 'update_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('job_notice', 'update_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('job_hunt', 'update_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
