"""empty message

Revision ID: f1ff96c6db5f
Revises: 656ee0b6daf5
Create Date: 2022-05-29 14:27:39.648300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ff96c6db5f'
down_revision = '656ee0b6daf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_hunt', 'update_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('job_notice', 'update_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('job_open', 'update_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('user', 'updated',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'updated',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('job_open', 'update_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('job_notice', 'update_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('job_hunt', 'update_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
